Repository team-confeti/confeti-server, pull requests merged in 2025-04, with the labels that each got.

#287 fix [#286] 로그인 API에서 카카오 로그인 시 프로필 이미지를 S3 다운로드
  src/main/java/org/sopt/confeti/api/auth/facade/AuthFacade.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserInfoResponse.java
  src/main/java/org/sopt/confeti/auth/LoginService.java
  src/main/java/org/sopt/confeti/auth/dto/CreateUserDTO.java
  src/main/java/org/sopt/confeti/auth/dto/LoginResult.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
  src/main/java/org/sopt/confeti/domain/user/infra/repository/UserRepository.java
  src/main/java/org/sopt/confeti/global/common/constant/FolderPath.java
  src/main/java/org/sopt/confeti/global/util/FileDownloader.java
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: 🐞 BugFix

#290 feat [#288] 애플 로그인 시 기본 프로필 이미지 지정
  src/main/java/org/sopt/confeti/auth/LoginService.java
  src/main/java/org/sopt/confeti/auth/dto/CreateUserDTO.java
  src/main/java/org/sopt/confeti/global/common/constant/Default.java
  src/main/java/org/sopt/confeti/global/common/constant/FolderPath.java
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: ✨ Feature

#292 feat [#291] 페스티벌 더미데이터 등록 페이지 수정 및 수정 페이지, API 구현
  src/main/java/org/sopt/confeti/api/dummy/controller/DummyPageController.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/CreateFestivalDateRequest.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/CreateFestivalRequest.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/CreateFestivalStageRequest.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/CreateFestivalTimeRequest.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/DummyFestivalPreviewResponse.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/FixDummyFestivalDTO.java
  src/main/java/org/sopt/confeti/api/dummy/dto/festival/FixFestivalRequest.java
  src/main/java/org/sopt/confeti/api/dummy/facade/DummyFacade.java
  src/main/java/org/sopt/confeti/api/dummy/facade/dto/festival/request/CreateFestivalDTO.java
  src/main/java/org/sopt/confeti/api/dummy/facade/dto/festival/request/CreateFestivalDateDTO.java
  src/main/java/org/sopt/confeti/api/dummy/facade/dto/festival/request/CreateFestivalTimeDTO.java
  src/main/java/org/sopt/confeti/api/dummy/facade/dto/festival/response/DummyFestivalPreviewDTO.java
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/global/config/AppConfig.java
  src/main/resources/templates/dummy/festival-list.html
  src/main/resources/templates/dummy/festival.html
  src/main/resources/templates/dummy/fix-festival.html
Labels: ✨ Feature

#294 fix [#293] 페스티벌에 아티스트 추가 시 Performance 테이블에 동기화
  src/main/java/org/sopt/confeti/api/dummy/facade/DummyFacade.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: 🐞 BugFix

#305 feat [#302] 상위 아티스트 목록 조회 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserOnboardController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserOnboardTopArtistResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserOnboardTopArtistsResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserOnboardFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserOnboardTopArtistDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserOnboardTopArtistsDTO.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/music/vo/ConfetiMusic.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/music/vo/ConfetiMusicArtist.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIURL.java
  src/main/java/org/sopt/confeti/global/util/music/MusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/dto/chart/AppleMusicChartResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/chart/AppleMusicChartSongResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/chart/AppleMusicChartsResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/AppleMusicMusicArtistResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/AppleMusicMusicArtistsResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/AppleMusicMusicRelationshipsResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/AppleMusicMusicResponse.java
Labels: ✨ Feature

#309 feat [#308] 특정 아티스트와 관련된 아티스트 목록 조회 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserOnboardController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/onboard/UserOnboardRelatedArtistResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/onboard/UserOnboardRelatedArtistsResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserOnboardFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/onboard/UserOnboardRelatedArtistDTO.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/MusicAPIHandler.java
Labels: ✨ Feature

#303 feat [#298] 다가오는 공연 조회 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserFavoriteController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UpcomingPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UpcomingPerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: ✨ Feature

#311 feat [#304] 프로필 편집 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchUserInfoRequest.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/domain/user/User.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: ✨ Feature

#317 Refactor [#316] 타임테이블이 생성되어 있지 않을 경우 빈 객체를 반환하도록 수정
  src/main/java/org/sopt/confeti/api/user/controller/UserFavoriteController.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
Labels: 🛠️ Refactor

#321 feat [#310] Elastic Search 연동 작업
  .github/workflows/workflow-dev.yml
  .github/workflows/workflow-main.yml
  build.gradle
  src/main/java/org/sopt/confeti/api/dummy/controller/PerformanceSearchController.java
  src/main/java/org/sopt/confeti/api/dummy/facade/PerformanceSearchFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformanceDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformancesDTO.java
  src/main/java/org/sopt/confeti/domain/elastic_search/PerformanceDocument.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/PerformanceSearchService.java
  src/main/java/org/sopt/confeti/domain/elastic_search/infra/PerformanceSearchRepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/PerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/PerformancePreviewDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceDTORepository.java
  src/main/java/org/sopt/confeti/global/config/ElasticSearchConfig.java
Labels: ✨ Feature

#323 fix [#322] JVM의 힙 메모리 초기 값, 최대 값 설정
  Dockerfile
  src/main/java/org/sopt/confeti/global/config/ElasticSearchConfig.java
Labels: 🐞 BugFix

#325 feat [#324] 타임테이블에 페스티벌 추가 API에 추가된 이력을 기록하는 로직 추가
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/domain/user/User.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: ✨ Feature

#327 feat [#326] 타임테이블에 페스티벌 추가 이력 조회 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableHistoryResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableHistoryDTO.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: ✨ Feature

#329 feat [#328] 아티스트 연관 검색어 조회 API 구현
  src/main/java/org/sopt/confeti/api/artist/controller/ArtistController.java
  src/main/java/org/sopt/confeti/api/artist/dto/response/SearchACArtistResponse.java
  src/main/java/org/sopt/confeti/api/artist/dto/response/SearchACArtistsResponse.java
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/api/artist/facade/dto/response/SearchACArtistDTO.java
  src/main/java/org/sopt/confeti/api/artist/facade/dto/response/SearchACArtistsDTO.java
Labels: ✨ Feature

#331 feat [#320] confeti’s pick 추천 공연 조회 API 구현
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/RecommendPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/RecommendPerformancesResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecommendPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecommendPerformancesDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: ✨ Feature

#337 feat [#336] 예정된 공연 목록 조회 API 구현
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/IntendedPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/IntendedPerformancesResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ArtistPerformancesDetailDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/IntendedPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/IntendedPerformancesDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformanceAllDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformancesAllDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/common/constant/Default.java
  src/main/java/org/sopt/confeti/global/common/constant/PerformanceType.java
  src/main/java/org/sopt/confeti/global/config/WebMvcConfig.java
  src/main/java/org/sopt/confeti/global/converter/StringToPerformanceTypeConverter.java
Labels: ✨ Feature

#339 feat [#338] 상위 아티스트 목록 조회 개수 수정
  src/main/java/org/sopt/confeti/api/user/controller/UserOnboardController.java
  src/main/java/org/sopt/confeti/api/user/facade/UserOnboardFacade.java
Labels: ✨ Feature

#341 feat [#340] 검색어에서 요청 공연 타입 분석 API 구현
  build.gradle
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/AnalyzePerformanceTypeResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/AnalyzePerformanceTypeDTO.java
  src/main/java/org/sopt/confeti/global/common/constant/PerformanceKeyword.java
  src/main/java/org/sopt/confeti/global/util/MorphemeAnalyzer.java
Labels: ✨ Feature

#343 fix [#342] 아티스트 연관 검색어 조회 API에서 조회 결과가 없을 때 빈 값을 주도록 변경
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
Labels: 🐞 BugFix

#345 feat [#344] 아티스트 검색 API 구현
  src/main/java/org/sopt/confeti/api/artist/controller/ArtistController.java
  src/main/java/org/sopt/confeti/api/artist/dto/response/SearchArtistSingleResponse.java
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/api/artist/facade/dto/response/SearchArtistDTO.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/album/vo/ConfetiAlbum.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/artist/vo/ConfetiArtist.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
Labels: ✨ Feature

#349 feat [#274] MY 셋리스트 > 공연 전체보기 목록 조회 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistController.java
  src/main/java/org/sopt/confeti/domain/setlist/Setlist.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistMusic.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistSortType.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistType.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/GetAllSetlistsResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistSummaryDto.java
  src/main/java/org/sopt/confeti/domain/setlist/infra/repository/SetlistRepository.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: ✨ Feature

#353 feat [#352] MY 셋리스트 > 공연 추가 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/SetlistCreateRequest.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistCreateResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/infra/repository/SetlistRepository.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: ✨ Feature

#355 refactor [#354] 온보딩 API 최소 아티스트 개수 1개로 수정
  src/main/java/org/sopt/confeti/auth/OnboardService.java
Labels: 🛠️ Refactor

#357 feat [#356] MY 셋리스트 > 곡 추가 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/AddSetListMusicRequest.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/AddSetListMusicResponse.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: ✨ Feature

#360 feat [#358] Redis 설정 + MY 셋리스트 > 편집 시작 API 구현
  build.gradle
  src/main/java/org/sopt/confeti/api/setlist/SetlistEditController.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistMusic.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/AddSetListMusicRequest.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/SetlistMusicEditDto.java
  src/main/java/org/sopt/confeti/domain/setlist/infra/repository/SetlistMusicRepository.java
  src/main/java/org/sopt/confeti/domain/setlist/infra/repository/SetlistRepository.java
  src/main/java/org/sopt/confeti/global/config/RedisConfig.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistEditServiceTest.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: ✨ Feature

#364 refactor [362] 프로필 편집 API 요청값 String->MultipartFile 형태로 수정
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchUserInfoRequest.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: 🛠️ Refactor

#365 feat [#358] MY 셋리스트 > 항목 순서 변경 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistEditController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/SetlistMusicOrderUpdateRequest.java
  src/main/java/org/sopt/confeti/global/config/JacksonConfig.java
  src/main/java/org/sopt/confeti/global/config/RedisConfig.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistEditServiceTest.java
Labels: ✨ Feature

#368 feat [#367] MY 셋리스트 > 상세 조회 API 구현
  build.gradle
  src/main/java/org/sopt/confeti/api/setlist/SetlistController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/GetSetlistDetailResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistMusicResponseDto.java
  src/main/java/org/sopt/confeti/global/config/JacksonConfig.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: ✨ Feature

#370 feat [#369] MY 셋리스트 > 항목 삭제 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistEditController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/global/message/SuccessMessage.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistEditServiceTest.java
Labels: ✨ Feature

#373 fix [#372] ObjectMapper FAIL_ON_UNKNOWN_PROPERTIES 속성 비활성화
  src/main/java/org/sopt/confeti/global/config/JacksonConfig.java
Labels: 🐞 BugFix

#374 refactor [#371] 셋리스트 전체목록 조회 파라미터 값 수정
  src/main/java/org/sopt/confeti/api/setlist/SetlistController.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistSortType.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
Labels: 🛠️ Refactor

#376 feat [#361] 내 공연 관람 기록 조회 API 구현
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ConfetiRecordResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ConfetiRecordDTO.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/infra/repository/SetlistRepository.java
  src/main/java/org/sopt/confeti/domain/timetable_festival/application/TimetableFestivalService.java
  src/main/java/org/sopt/confeti/domain/timetable_festival/infra/repository/TimetableFestivalRepository.java
Labels: ✨ Feature

#377 feat [#366] 예정된 공연 목록 조회 API에서 공연명을 포함해 검색하도록 추가
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/IntendedPerformancesDTO.java
  src/main/java/org/sopt/confeti/domain/elastic_search/PerformanceDocument.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/PerformanceSearchService.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/dto/response/SearchPerformanceResult.java
  src/main/java/org/sopt/confeti/domain/elastic_search/infra/PerformanceSearchOperator.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/PerformanceDTO.java
Labels: ✨ Feature

#378 feat [#375] MY 셋리스트 > 편집 완료 API 구현
  src/main/java/org/sopt/confeti/api/setlist/SetlistEditController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/global/message/SuccessMessage.java
Labels: ✨ Feature

#384 feat [#383] 예정된 공연 목록 조회 API 응답 값에 type, typeId 추가
  src/main/java/org/sopt/confeti/api/dummy/controller/PerformanceSearchController.java
  src/main/java/org/sopt/confeti/api/dummy/facade/PerformanceSearchFacade.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/IntendedPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/IntendedPerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/elastic_search/PerformanceDocument.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/dto/response/SearchPerformanceResult.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/PerformanceDTO.java
Labels: ✨ Feature

#386 feat [#385] 셋리스트 공연 추가를 위한 공연 검색 API 구현
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistController.java
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistEditController.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/SetlistSearchPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/SetlistSearchPerformancesResponse.java
  src/main/java/org/sopt/confeti/api/setlist/facade/SetlistFacade.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/SearchPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/SearchPerformancesDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/common/AnalyzeSearchTermResult.java
  src/main/java/org/sopt/confeti/global/util/MorphemeAnalyzer.java
Labels: ✨ Feature

#391 feat [#389] MY 셋리스트 > 곡 검색 API 구현
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistSearchController.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/search/SetlistSearchMusicResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/search/SetlistSearchMusicsResponse.java
  src/main/java/org/sopt/confeti/api/setlist/facade/SetlistSearchFacade.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/search/SetlistSearchMusicDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/search/SetlistSearchMusicsDTO.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/MusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/AppleMusicMusicsResponse.java
  src/main/java/org/sopt/confeti/global/util/music/dto/search/AppleMusicSearchResultsResponse.java
Labels: ✨ Feature

#394 feat [#393] 인기 검색어 집계를 위한 Elastic Search 구성 및 연동 작업
  src/main/java/org/sopt/confeti/domain/elastic_search/SearchTermDocument.java
  src/main/java/org/sopt/confeti/domain/elastic_search/infra/SearchTermOperator.java
Labels: ✨ Feature

#397 feat [#396] MY 셋리스트 > 편집 취소 API 구현
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistEditController.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/global/config/RedisConfig.java
Labels: ✨ Feature

#398 feat [#395] 인기 검색어 목록 조회 API 구현
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/search_term/controller/SearchTermController.java
  src/main/java/org/sopt/confeti/api/search_term/dto/response/PopularTermResponse.java
  src/main/java/org/sopt/confeti/api/search_term/dto/response/PopularTermsResponse.java
  src/main/java/org/sopt/confeti/api/search_term/facade/SearchTermFacade.java
  src/main/java/org/sopt/confeti/api/search_term/facade/dto/response/PopularTermDTO.java
  src/main/java/org/sopt/confeti/api/search_term/facade/dto/response/PopularTermsDTO.java
  src/main/java/org/sopt/confeti/domain/elastic_search/SearchTermDocument.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/PerformanceSearchService.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/SearchTermService.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/dto/response/PopularTermResult.java
  src/main/java/org/sopt/confeti/domain/elastic_search/infra/SearchTermOperator.java
  src/main/java/org/sopt/confeti/domain/elastic_search/infra/SearchTermRepository.java
Labels: ✨ Feature

#400 feat [#399] 검색화면 > 유효한 콘서트/페스티벌 목록 조회 API 구현
  build.gradle
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/api/performance/dto/request/GetExpectedPerformanceRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ExpectedPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ExpectedPerformancesResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/GetExpectedPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/GetExpectedPerformancesDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ExpectedPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ExpectedPerformancesDTO.java
  src/main/java/org/sopt/confeti/api/search_term/controller/SearchTermController.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceCriteriaRepository.java
Labels: ✨ Feature

#402 feat [#401] My setlists > 공연 추가를 위한 공연 검색 API 응답값에 type, typeId 추가
  src/main/java/org/sopt/confeti/api/setlist/dto/response/search/SetlistSearchPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/search/SearchPerformanceDTO.java
Labels: ✨ Feature

#404 fix [#403] 셋리스트 관련 API 응답 형태 수정
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/GetSetlistDetailResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistSummaryDto.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: 🐞 BugFix

#407 fix [#406] Setlists <> User cascade 설정 추가
  src/main/java/org/sopt/confeti/domain/setlist/Setlist.java
  src/main/java/org/sopt/confeti/domain/user/User.java
Labels: 🐞 BugFix

#410 fix [#409] 회원탈퇴 시 카카오/애플 Unlink 작업 추가
  src/main/java/org/sopt/confeti/api/auth/facade/AuthFacade.java
  src/main/java/org/sopt/confeti/auth/WithdrawService.java
  src/main/java/org/sopt/confeti/domain/token/infra/AppleTokenRepository.java
  src/main/java/org/sopt/confeti/global/module/rest_client/builder/step/ResponseStep.java
  src/main/java/org/sopt/confeti/global/module/rest_client/builder/step/impl/ResponseStepImpl.java
  src/main/java/org/sopt/confeti/global/oauth/AppleApiClient.java
  src/main/java/org/sopt/confeti/global/oauth/KakaoApiClient.java
  src/main/java/org/sopt/confeti/global/oauth/OAuthApiClient.java
Labels: ✨ Feature

#411 feat [#405] Apple Music API의 Rate Limit 해결을 위한 Redis 캐싱
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/MusicPage.java
Labels: ✨ Feature

#415 fix [#414] Resolver에서 keySet 레퍼런스 전달로 인한 데이터 불일치 문제 해결
  src/main/java/org/sopt/confeti/global/resolver/music_api/album/AlbumResolver.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/artist/ArtistResolver.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/music/MusicResolver.java
Labels: 🐞 BugFix

#417 setting [#416] RestClient 임시 로그 출력
  src/main/java/org/sopt/confeti/global/module/rest_client/builder/step/impl/ResponseStepImpl.java
Labels: ⚙️ Setting

#419 setting [#418] RestClient 임시 로그 출력
  src/main/java/org/sopt/confeti/global/module/rest_client/builder/step/impl/ResponseStepImpl.java
Labels: ⚙️ Setting

#422 refactor [#421] 사용되지 않는 앨범 발매일자 제거
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ConcertArtistDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailArtistDTO.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/album/AlbumResolver.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/album/vo/ConfetiAlbum.java
  src/main/java/org/sopt/confeti/global/util/music/dto/album/AppleMusicAlbumAttributesResponse.java
Labels: 🛠️ Refactor

#427 fix [#426] 전체 대상 공연 목록을 조회할 때 지난 공연이 뜨지 않도록 수정
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: 🐞 BugFix
