Repository team-confeti/confeti-server, pull requests merged in 2025-09, with the labels that each got.

#532 SERVER-16 CI workflow 수정
  .github/workflows/workflow-dev.yml
Labels: 🌏 Deploy

#535 SERVER-21 elasticSearch 서버 환경 변화에 따른 config 수정
  src/main/java/org/sopt/confeti/global/config/ElasticSearchConfig.java
Labels: ✨ Feature

#538 CONFETI-5 refactor: OpenAPI, Swagger 관련 코드 및 파일 제거
  .github/workflows/workflow-dev.yml
  .github/workflows/workflow-main.yml
  Dockerfile
  build.gradle
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
  src/main/java/org/sopt/confeti/global/config/WebMvcConfig.java
  src/test/java/org/sopt/confeti/restdocs/api/artist/ArtistTest.java
  src/test/java/org/sopt/confeti/restdocs/api/performance/PerformanceTest.java
  src/test/java/org/sopt/confeti/restdocs/api/search_term/.gitkeep
  src/test/java/org/sopt/confeti/restdocs/api/setlist/.gitkeep
  src/test/java/org/sopt/confeti/restdocs/api/user/UserFavoriteTest.java
  src/test/java/org/sopt/confeti/restdocs/api/user/UserTimetableTest.java
  src/test/java/org/sopt/confeti/restdocs/base/APIBaseTest.java
  src/test/java/org/sopt/confeti/restdocs/base/ElasticsearchTestConfig.java
  src/test/java/org/sopt/confeti/restdocs/base/SharedTestContainers.java
  src/test/java/org/sopt/confeti/restdocs/base/TestDataManager.java
Labels: 🛠️ Refactor

#537 SERVER-24 Apple Music API 관련 엔티티 작성
  src/main/java/org/sopt/confeti/domain/applemusic/artist/Artist.java
  src/main/java/org/sopt/confeti/domain/applemusic/artist/infra/repository/ArtistRepository.java
  src/main/java/org/sopt/confeti/domain/applemusic/artistsong/ArtistSong.java
  src/main/java/org/sopt/confeti/domain/applemusic/artistsong/infra/repository/ArtistSongRepository.java
  src/main/java/org/sopt/confeti/domain/applemusic/song/Song.java
  src/main/java/org/sopt/confeti/domain/applemusic/song/infra/repository/SongRepository.java
  src/main/java/org/sopt/confeti/domain/applemusic/topartist/TopArtist.java
  src/main/java/org/sopt/confeti/domain/applemusic/topartist/infra/repository/TopArtistRepository.java
Labels: ✨ Feature

#540 CONFETI-27 feat: Swagger 초기 세팅
  build.gradle
  src/main/java/org/sopt/confeti/api/artist/controller/ArtistController.java
  src/main/java/org/sopt/confeti/global/annotation/UserId.java
  src/main/java/org/sopt/confeti/global/common/swagger/AuthErrorResponses.java
  src/main/java/org/sopt/confeti/global/common/swagger/BadRequestErrorResponse.java
  src/main/java/org/sopt/confeti/global/common/swagger/CommonErrorResponses.java
  src/main/java/org/sopt/confeti/global/common/swagger/ConflictErrorResponse.java
  src/main/java/org/sopt/confeti/global/common/swagger/TypeMismatchErrorResponse.java
  src/main/java/org/sopt/confeti/global/config/SwaggerConfig.java
  src/main/java/org/sopt/confeti/global/exception/ErrorResponseConstant.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
Labels: ✨ Feature
