Repository team-confeti/confeti-server, pull requests merged in 2025-06, with the labels that each got.

#453 refactor [#452] profileUrl(String) -> profileFile(MultipartFile) 형식 변경
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchUserInfoRequest.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: 🛠️ Refactor

#462 fix [#461] 셋리스트 곡 검색 API에서 조회 결과가 없을 경우 빈 리스트 반환
  src/main/java/org/sopt/confeti/global/util/music/AppleMusicAPIHandler.java
  src/main/java/org/sopt/confeti/global/util/music/dto/music/MusicPage.java
Labels: 🐞 BugFix

#466 refactor [#465] 음악 제목 변수 네이밍 변경
  src/main/java/org/sopt/confeti/api/performance/dto/response/RecommendMusicResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecommendMusicDTO.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/search/SetlistSearchArtistMusicResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/search/SetlistSearchMusicResponse.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/search/SetlistSearchArtistMusicDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/search/SetlistSearchMusicDTO.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/music/MusicResolver.java
  src/main/java/org/sopt/confeti/global/resolver/music_api/music/vo/ConfetiMusic.java
Labels: 🛠️ Refactor

#468 refactor [#467] 파일명이 Base64로 인코딩 되도록 수정
  .gitignore
  src/main/java/org/sopt/confeti/global/util/FileNameGenerator.java
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: 🛠️ Refactor

#474 refactor [#473] 파일 등록 시 이름에서 슬레시 제거 및 인코딩해서 URL 반환
  src/main/java/org/sopt/confeti/global/util/FileNameGenerator.java
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: 🛠️ Refactor

#480 feat [#479] 온보딩 여부 조회 API 구현
  src/main/java/org/sopt/confeti/api/auth/controller/AuthController.java
  src/main/java/org/sopt/confeti/api/auth/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/api/auth/dto/response/GetIsOnboardingResponse.java
  src/main/java/org/sopt/confeti/api/auth/facade/AuthFacade.java
  src/main/java/org/sopt/confeti/api/auth/facade/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/api/auth/facade/dto/response/GetIsOnboardingDTO.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
  src/main/resources/static/swagger-ui/openapi3.yaml
Labels: ✨ Feature
