Repository team-confeti/confeti-server, pull requests merged in 2025-01, with the labels that each got.

#3 chore [#1] 초기 프로젝트 설정
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/sopt/confeti/ConfetiApplication.java
  src/main/java/org/sopt/confeti/annotation/.gitkeep
  src/main/java/org/sopt/confeti/api/controller/.gitkeep
  src/main/java/org/sopt/confeti/api/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/api/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/api/facade/.gitkeep
  src/main/java/org/sopt/confeti/api/vo/.gitkeep
  src/main/java/org/sopt/confeti/auth/filter/.gitkeep
  src/main/java/org/sopt/confeti/auth/jwt/.gitkeep
  src/main/java/org/sopt/confeti/domain/model/application/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/domain/model/application/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/domain/model/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/global/config/.gitkeep
  src/main/java/org/sopt/confeti/global/exception/.gitkeep
  src/main/java/org/sopt/confeti/global/util/.gitkeep
  src/test/java/org/sopt/confeti/ConfetiApplicationTests.java
Labels: 🪡 Init

#10 init [#9] CORS 설정
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
  src/main/java/org/sopt/confeti/global/config/SecurityConfig.java
Labels: 🪡 Init

#12 init [#11] Dockerfile 작성
  Dockerfile
Labels: 📃 Docs, 🪡 Init

#15 init [#7] api 응답 인터페이스, 클래스 구현
  build.gradle
  src/main/java/org/sopt/confeti/global/common/BaseResponse.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
  src/main/java/org/sopt/confeti/global/message/SuccessMessage.java
Labels: ✨ Feature, 🪡 Init

#16 init [#14] Discord Web Hook 설정
  .github/workflows/discord-pr-hook.yml
Labels: 🪡 Init

#17 init [#13] CI/CD 파일 작성
  .github/workflows/workflow-dev.yml
  .github/workflows/workflow-main.yml
Labels: 🪡 Init

#20 hotfix [#19] gitssh에 port 지정
  .github/workflows/discord-pr-hook.yml
  .github/workflows/workflow-main.yml
Labels: 🐞 BugFix

#22 hotfix [#21] Git Action 빌드 자바 버전을 21로 변경
  .github/workflows/workflow-main.yml
Labels: 🐞 BugFix

#24 hotfix [#23] Dockerfile 자바 버전 21로 업그레이드 (멍충 이슈....)
  Dockerfile
Labels: 🐞 BugFix

#26 init [#25] 전역 예외 처리 기능 구현
  src/main/java/org/sopt/confeti/global/exception/ConfetiException.java
  src/main/java/org/sopt/confeti/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/confeti/global/exception/HttpRequestMethodNotSupportedException.java
  src/main/java/org/sopt/confeti/global/exception/MethodArgumentTypeMismatchException.java
  src/main/java/org/sopt/confeti/global/exception/NotFoundException.java
  src/main/java/org/sopt/confeti/global/exception/UnauthorizedException.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
Labels: ✨ Feature, 🪡 Init

#28 fix [#27] S3 구성 파일 제거 및 핸들러 수정
  build.gradle
  src/main/java/org/sopt/confeti/global/config/S3Config.java
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: 🐞 BugFix

#32 fix [#31] 버전 호환성을 고려해 logback.xml 업데이트
  src/main/resources/logback.xml
Labels: 🐞 BugFix

#36 feat [#35] JpaRepository 작성
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/concert/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/concert/infra/repository/ConcertRepository.java
  src/main/java/org/sopt/confeti/domain/concertartist/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/concertartist/infra/repository/ConcertArtistRepository.java
  src/main/java/org/sopt/confeti/domain/concertfavorite/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/concertfavorite/infra/repository/ConcertFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
  src/main/java/org/sopt/confeti/domain/festivalartist/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivalartist/infra/repository/FestivalArtistRepository.java
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/repository/FestivalDateRepository.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivalfavorite/infra/repository/FestivalFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/festivalstage/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivalstage/infra/repository/FestivalStageRepository.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
  src/main/java/org/sopt/confeti/domain/user/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/user/infra/repository/UserRepository.java
  src/main/java/org/sopt/confeti/domain/usertimetable/infra/repository/.gitkeep
  src/main/java/org/sopt/confeti/domain/usertimetable/infra/repository/UserTimetableRepository.java
Labels: ✨ Feature

#39 feat [#38] erd 이미지 경로, 부제목 추가
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
Labels: 🛠️ Refactor

#44 refactor [#42] erd festivalTimes 테이블 추가
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
  src/main/java/org/sopt/confeti/domain/festivalartist/FestivalArtist.java
  src/main/java/org/sopt/confeti/domain/festivalstage/FestivalStage.java
  src/main/java/org/sopt/confeti/domain/festivaltime/FestivalTime.java
  src/main/java/org/sopt/confeti/domain/festivaltime/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivaltime/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivaltime/infra/repository/FestivalTimeRepository.java
  src/main/java/org/sopt/confeti/domain/usertimetable/UserTimetable.java
Labels: 🛠️ Refactor

#51 fix [#50] FestivalTime @OneToMany 관계에서 mappedBy가 잘못된 것을 수정
  src/main/java/org/sopt/confeti/domain/festivaltime/FestivalTime.java
Labels: 🐞 BugFix

#54 refactor [#53] 각 엔티티에 Artist 임베드 추가
  src/main/java/org/sopt/confeti/domain/artistfavorite/ArtistFavorite.java
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/concertartist/ConcertArtist.java
  src/main/java/org/sopt/confeti/domain/concertfavorite/ConcertFavorite.java
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
  src/main/java/org/sopt/confeti/domain/festivalartist/FestivalArtist.java
  src/main/java/org/sopt/confeti/domain/festivaldate/FestivalDate.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/FestivalFavorite.java
  src/main/java/org/sopt/confeti/domain/festivalstage/FestivalStage.java
  src/main/java/org/sopt/confeti/domain/festivaltime/FestivalTime.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/TimetableFestival.java
  src/main/java/org/sopt/confeti/domain/user/User.java
  src/main/java/org/sopt/confeti/domain/usertimetable/UserTimetable.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/ConfetiArtist.java
Labels: 🛠️ Refactor

#61 refactor [#60] 로그 파일 삭제
  src/main/resources/logback.xml
Labels: 🛠️ Refactor

#65 release [#62] 배포를 위해 임의의 공백 추가
  .gitignore
Labels: 🌏 Deploy

#70 hotfix [#69] ArtistResolver에서 같은 객체를 계속 탐색하는 것을 수정
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/ArtistResolver.java
Labels: 🐞 BugFix

#84 feat [#67] 페스티벌 정보 조회 API 구현
  build.gradle
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailArtistResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailDateResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailArtistDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailDateDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailStageDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailTimeDTO.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festivalartist/FestivalArtist.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/application/FestivalFavoriteService.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/infra/repository/FestivalFavoriteRepository.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/ArtistResolver.java
Labels: ✨ Feature

#101 refactor [#100] DateConvertor static 클래스로 변경
  src/main/java/org/sopt/confeti/annotation/Convertor.java
  src/main/java/org/sopt/confeti/global/util/DateConvertor.java
Labels: 🛠️ Refactor

#106 refactor [#105] 날짜 매핑 방법 변경
  src/main/java/org/sopt/confeti/api/artist/dto/response/SearchArtistSingleResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalDateRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalTimeRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ConcertDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserFavoriteResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserInfoResponse.java
  src/main/java/org/sopt/confeti/global/util/DateConvertor.java
Labels: 🛠️ Refactor

#108 feat [#107] 타임테이블 페스티벌 삭제 API 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/domain/concert/application/ConcertService.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/application/TimetableFestivalService.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: ✨ Feature

#115 fix [#114] SpotifyAPIHandler 예외 처리 수정
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🐞 BugFix

#120 release 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/user/controller/UserFavoriteController.java
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/AddTimetableFestivalArtistRequest.java
  src/main/java/org/sopt/confeti/api/user/dto/request/AddTimetableFestivalRequest.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserFavoritePerformanceResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserFavoritePerformancesResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/request/AddTimetableFestivalArtiestDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/request/AddTimetableFestivalDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformanceDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformancesDTO.java
  src/main/java/org/sopt/confeti/domain/concert/application/ConcertService.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/application/TimetableFestivalService.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
  src/main/java/org/sopt/confeti/domain/user/application/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/domain/view/performance/PerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/.gitkeep
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/common/constant/PerformanceType.java
  src/main/java/org/sopt/confeti/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
  src/main/java/org/sopt/confeti/global/message/SuccessMessage.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🌏 Deploy

#123 [release] 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🌏 Deploy

#125 [release] 배포했습니다.
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/TimetableFestival.java
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
  src/main/java/org/sopt/confeti/domain/user/User.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
  src/main/java/org/sopt/confeti/domain/user/infra/repository/UserRepository.java
  src/main/java/org/sopt/confeti/domain/usertimetable/UserTimetable.java
Labels: 🌏 Deploy

#129 fix [#127] SpotifyAPIHandler 리프레시 토큰 재발급 로직 재구성 및 마지막 발매 일자 가져오는 방법 변경
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🐞 BugFix

#130 [release] 배포합니다.
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🌏 Deploy

#131 [release] 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceReservationDetailResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceReservationResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/PerformanceReservationDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/PerformanceReservationDetailDTO.java
  src/main/java/org/sopt/confeti/domain/concertfavorite/application/ConcertFavoriteService.java
  src/main/java/org/sopt/confeti/domain/concertfavorite/infra/repository/ConcertFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/application/FestivalFavoriteService.java
  src/main/java/org/sopt/confeti/domain/festivalfavorite/infra/repository/FestivalFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/PerformanceTicketDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: 🌏 Deploy

#135 [release] 배포합니다.
  src/main/java/org/sopt/confeti/api/user/controller/UserFavoriteController.java
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/TimetablesToAddFestivalResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/TimetablesToAddResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/TimetableToAddDTO.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festival/application/dto/FestivalCursorDTO.java
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
  src/main/java/org/sopt/confeti/global/common/CursorPage.java
  src/main/java/org/sopt/confeti/global/message/ErrorMessage.java
Labels: 🌏 Deploy

#138 fix [#137] CORS 허용 도메인에 클라이언트 www 도메인 추가
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
Labels: 🐞 BugFix

#132 feat [#104] 타임테이블에 등록된 시간표 조회 Api 구현
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalArtistResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalStageResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalTimeResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalArtistDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalBasicDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalStageDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalTimeDTO.java
  src/main/java/org/sopt/confeti/domain/festivaldate/application/FestivalDateService.java
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/repository/FestivalDateRepository.java
Labels: ✨ Feature

#141 fix [#140] 날짜 값 변경해서 조회
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
Labels: 🐞 BugFix

#142 [release] 배포합니다.
  src/main/java/org/sopt/confeti/domain/timetablefestival/infra/repository/TimetableFestivalRepository.java
Labels: 🌏 Deploy

#150 [release] ERD 수정 및 API 수정에 따른 반영을 위해 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ConcertDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceReservationDetailResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceReservationResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateFestivalDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ConcertDetailDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/FestivalDetailDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/PerformanceReservationDetailDTO.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserFavoritePerformanceResponse.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserFavoritePerformancesResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserFavoritePerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/festival/Festival.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/PerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/PerformanceTicketDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceDTORepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/util/DateConvertor.java
Labels: 🌏 Deploy

#154 fix [#153] 콘서트 정보 조회 API에 좋아요 정보가 전달되지 않는 것을 수정
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ConcertDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ConcertDetailDTO.java
Labels: 🐞 BugFix

#157 fix [#156] 타임테이블 시간표 조회 API 응답값 수정
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalTimeResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalBasicDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalStageDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalTimeDTO.java
  src/main/java/org/sopt/confeti/domain/festivaldate/application/FestivalDateService.java
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/repository/FestivalDateRepository.java
  src/main/java/org/sopt/confeti/domain/usertimetable/application/UserTimetableService.java
  src/main/java/org/sopt/confeti/domain/usertimetable/infra/repository/UserTimetableRepository.java
Labels: 🐞 BugFix

#160 refactor [#159] 스포티파이에 존재하지 않는 아티스트인 경우 404 응답 처리
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🛠️ Refactor

#161 [release] 수정사항을 반영해 배포합니다.
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalDateRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateFestivalTimeRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/ConcertDetailInfoResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateFestivalDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/ConcertDetailDTO.java
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchTimetableListRequest.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchTimetableRequest.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserTimetableFestivalTimeResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/request/PatchTimetableDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/request/PatchTimetableListDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalBasicDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalStageDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserTimetableFestivalTimeDTO.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festivaldate/application/FestivalDateService.java
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/repository/FestivalDateRepository.java
  src/main/java/org/sopt/confeti/domain/usertimetable/UserTimetable.java
  src/main/java/org/sopt/confeti/domain/usertimetable/application/UserTimetableService.java
  src/main/java/org/sopt/confeti/domain/usertimetable/infra/repository/UserTimetableRepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/global/message/SuccessMessage.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🌏 Deploy

#163 fix [#162] 콘서트 좋아요 추가 - 좋아요가 있을 때 409 반환
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
Labels: 🐞 BugFix

#165 fix [#164] 트랜잭션 추가
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
Labels: 🐞 BugFix

#168 refactor [#167] 유저 정보 조회 API - 컨트롤러 계층에서 url 생성하도록 리펙토링
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserInfoResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserInfoDTO.java
Labels: 🛠️ Refactor

#166 [release] 수정사항 반영을 위해 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/RecentPerformanceResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/RecentPerformancesResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecentPerformanceDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecentPerformancesDTO.java
  src/main/java/org/sopt/confeti/api/user/facade/UserFavoriteFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/application/ArtistFavoriteService.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/concert/application/ConcertService.java
  src/main/java/org/sopt/confeti/domain/concert/infra/repository/ConcertRepository.java
  src/main/java/org/sopt/confeti/domain/festival/application/FestivalService.java
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/request/GetPerformanceIdRequest.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/GetPerformanceIdResponse.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
Labels: 🌏 Deploy

#171 [release] 수정사항 반영을 위해 배포합니다.
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/controller/UserTimetableController.java
  src/main/java/org/sopt/confeti/api/user/dto/response/UserInfoResponse.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/UserTimetableFacade.java
  src/main/java/org/sopt/confeti/api/user/facade/dto/response/UserInfoDTO.java
  src/main/java/org/sopt/confeti/domain/usertimetable/infra/repository/UserTimetableRepository.java
Labels: 🌏 Deploy

#173 fix [#172] 이미 추가한 페스티벌은 조회되지 않도록 수정
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
Labels: 🐞 BugFix

#174 [release] 수정사항을 반영하여 배포합니다.
  src/main/java/org/sopt/confeti/domain/festival/infra/repository/FestivalRepository.java
Labels: 🌏 Deploy

#178 [release] CORS 허용 도메인 추가 반영을 위해 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/RecentPerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
Labels: 🌏 Deploy

#184 fix [#183] 관심 있는 아티스트 목록 조회 개수 수정
  src/main/java/org/sopt/confeti/domain/artistfavorite/application/ArtistFavoriteService.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
Labels: 🐞 BugFix

#185 [release] 배포합니다! 포배포
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceByArtistDetailResponse.java
  src/main/java/org/sopt/confeti/api/performance/dto/response/PerformanceByArtistResponse.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/PerformanceByArtistListDTO.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/application/ArtistFavoriteService.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/concertfavorite/application/ConcertFavoriteService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/PerformanceCursorDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
Labels: 🌏 Deploy

#187 feat [#186] 콘서트 생성 API 구현
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateConcertArtistRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateConcertRequest.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateConcertArtistDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateConcertDTO.java
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/concert/application/ConcertService.java
  src/main/java/org/sopt/confeti/domain/concertartist/ConcertArtist.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
Labels: ✨ Feature

#188 [release] 배포합니다.
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateConcertArtistRequest.java
  src/main/java/org/sopt/confeti/api/performance/dto/request/CreateConcertRequest.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateConcertArtistDTO.java
  src/main/java/org/sopt/confeti/api/performance/facade/dto/request/CreateConcertDTO.java
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
  src/main/java/org/sopt/confeti/domain/concert/application/ConcertService.java
  src/main/java/org/sopt/confeti/domain/concertartist/ConcertArtist.java
  src/main/java/org/sopt/confeti/domain/view/performance/Performance.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
Labels: 🌏 Deploy

#191 fix [#190] 변경된 컬럼값이 적용되지 않은 것을 수정
  build.gradle
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
Labels: 🐞 BugFix

#192 fix [#189] 아티스트 검색 결과가 없을 시 NULL 반환으로 변경
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🐞 BugFix

#195 fix [#194] 기존 아티스트 아이디 값 조회 로직 변경
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/application/ArtistFavoriteService.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
Labels: 🐞 BugFix

#196 [release] 배포합니다!
  build.gradle
  src/main/java/org/sopt/confeti/api/artist/facade/ArtistFacade.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/application/ArtistFavoriteService.java
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/repository/ArtistFavoriteRepository.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🌏 Deploy

#198 fix [#197] 공연 정보가 없는 아티스트를 좋아요 했을 때 전체 대상으로 조회하도록 변경
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
Labels: 🐞 BugFix

#203 fix [#202] 콘서트와 콘서트 아티스트 영속 생명주기 동기화
  src/main/java/org/sopt/confeti/domain/concert/Concert.java
Labels: 🐞 BugFix

#210 fix [#209] 예약 URL -> 배너 경로 가져오는 것으로 변경
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/DummyPerformanceDTO.java
Labels: 🐞 BugFix

#211 [release] 최최종 배포
  src/main/java/org/sopt/confeti/api/performance/facade/dto/response/DummyPerformanceDTO.java
Labels: 🌏 Deploy

#217 feat [#216] 하나의 아티스트 아이디 값이 여러 개의 객체에 매핑될 수 있도록 수정
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: ✨ Feature

#219 refactor [#218] 관심있는 아티스트 목록 조회에서 최대 개수 4개로 변경
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceDTORepository.java
Labels: 🛠️ Refactor

#221 fix [#220] 스포티파이 앨범 최신일자 조회 수정
  src/main/java/org/sopt/confeti/global/util/artistsearcher/ArtistResolver.java
  src/main/java/org/sopt/confeti/global/util/artistsearcher/SpotifyAPIHandler.java
Labels: 🐞 BugFix
