Repository team-confeti/confeti-server, pull requests merged in 2025-05, with the labels that each got.

#435 fix [#434] 예정된 공연 조회 API에서 날짜가 지난 공연과 중복된 공연이 나오지 않도록 수정
  src/main/java/org/sopt/confeti/api/performance/controller/PerformanceController.java
  src/main/java/org/sopt/confeti/api/performance/facade/PerformanceFacade.java
  src/main/java/org/sopt/confeti/domain/elastic_search/application/PerformanceSearchService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/dto/response/PerformanceDTO.java
  src/main/java/org/sopt/confeti/domain/view/performance/infra/repository/PerformanceRepository.java
  src/main/java/org/sopt/confeti/global/common/constant/Default.java
Labels: 🐞 BugFix

#441 refactor [#440] S3 Signed URL 제거
  src/main/java/org/sopt/confeti/global/util/S3FileHandler.java
Labels: 🛠️ Refactor

#439 feat [#438] 디스코드 회원가입 알림 연동
  src/main/java/org/sopt/confeti/api/auth/facade/AuthFacade.java
  src/main/java/org/sopt/confeti/auth/WebhookService.java
Labels: ✨ Feature

#443 refactor [#442] 페스티벌 조회 API festivalAt 포맷 변경
  src/main/java/org/sopt/confeti/api/performance/dto/response/FestivalDetailDateResponse.java
Labels: 🛠️ Refactor

#444 refactor [#437] 셋리스트 관련 API Facade 패턴 적용
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistController.java
  src/main/java/org/sopt/confeti/api/setlist/controller/SetlistEditController.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/GetAllSetlistsResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/GetSetlistDetailResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/SetlistMusicResponse.java
  src/main/java/org/sopt/confeti/api/setlist/dto/response/SetlistSummaryResponse.java
  src/main/java/org/sopt/confeti/api/setlist/facade/SetlistFacade.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/request/SetlistAddMusicDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/request/SetlistCreateRequestDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/request/SetlistMusicEditDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/request/SetlistUpdateMusicOrderDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/SetlistAddMusicResponseDTO.java
  src/main/java/org/sopt/confeti/api/setlist/facade/dto/response/SetlistCreateResponseDTO.java
  src/main/java/org/sopt/confeti/domain/setlist/SetlistMusic.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistEditService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/SetlistService.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/request/SetlistMusicOrderUpdateRequest.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/AddSetListMusicResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/GetAllSetlistsResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistCreateResponse.java
  src/main/java/org/sopt/confeti/domain/setlist/application/dto/response/SetlistMusicResponseDto.java
  src/main/java/org/sopt/confeti/domain/view/performance/application/PerformanceService.java
  src/main/java/org/sopt/confeti/global/config/RedisConfig.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistEditServiceTest.java
  src/test/java/org/sopt/confeti/domain/setlist/application/SetlistServiceTest.java
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactor

#448 refactor [#445] 프로필 편집 API 로직 수정
  src/main/java/org/sopt/confeti/api/user/controller/UserInfoController.java
  src/main/java/org/sopt/confeti/api/user/dto/request/PatchUserInfoRequest.java
  src/main/java/org/sopt/confeti/api/user/facade/UserInfoFacade.java
  src/main/java/org/sopt/confeti/domain/user/application/UserService.java
Labels: 🛠️ Refactor
