Repository team-confeti/confeti-server, pull requests merged in 2025-03, with the labels that each got.

#238 feat [#222] README 작성
  README.md
  src/main/java/org/sopt/confeti/domain/artistfavorite/infra/ArtistFavoriteArtistStrategy.java
  src/main/java/org/sopt/confeti/domain/concert/infra/ConcertArtistStrategy.java
  src/main/java/org/sopt/confeti/domain/festival/infra/FestivalArtistStrategy.java
  src/main/java/org/sopt/confeti/domain/festivaldate/infra/FestivalDateArtistStrategy.java
  src/main/java/org/sopt/confeti/domain/festivaltime/application/dto/request/.gitkeep
  src/main/java/org/sopt/confeti/domain/festivaltime/application/dto/response/.gitkeep
Labels: 📃 Docs

#246 feat [#245] CORS 허용 도메인 추가
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
Labels: ✨ Feature

#249 refactor [#248] CORS 전체 도메인 허용 설정
  src/main/java/org/sopt/confeti/global/config/CorsConfig.java
Labels: 🛠️ Refactor

#253 fix [#252] 폴더 경로 생성 시 구분자("/")가 한 번 들어가도록 수정
  src/main/java/org/sopt/confeti/global/common/constant/FolderPath.java
Labels: 🐞 BugFix
